feat: update ci-cd pipeline 13

diff --git a/.github/actions/create-tag/action.yml b/.github/actions/create-tag/action.yml
--- a/.github/actions/create-tag/action.yml
+++ b/.github/actions/create-tag/action.yml
@@ -16,24 +16,27 @@ runs:
     - name: Validate version format
       run: |
         VERSION=$(node -p "require('./package.json').version")
-        if git rev-parse "$TAG" >/dev/null 2>&1; then
-          echo "Tag $TAG already exists, skipping tag creation."
-        else
-          git tag -a $TAG -m "Release version $TAG"
+        if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "Version format is invalid. Please follow semver format (x.y.z)"
+          exit 1
         fi
+      shell: bash
+
+    - name: Fetch all tags
+      run: git fetch --tags
       shell: bash
 
     - name: Tag version
       run: |
         TAG="v$(node -p -e "require('./package.json').version")"
+        echo "Tag to create: $TAG"
         if git rev-parse "$TAG" >/dev/null 2>&1; then
           echo "Tag $TAG already exists"
           exit 1
         fi
-        git tag -a $TAG -m "Release version $TAG"
+        git tag -a "$TAG" -m "Release version $TAG"
       shell: bash
 
     - name: Push tags to GitHub
-      run: |
-        git push origin "$TAG" || { echo "Failed to push tags"; exit 1; }
+      run: git push origin "$TAG"
       shell: bash
