feat: update ci-cd pipeline 11

diff --git a/.github/actions/create-tag/action.yml b/.github/actions/create-tag/action.yml
--- a/.github/actions/create-tag/action.yml
+++ b/.github/actions/create-tag/action.yml
@@ -16,9 +16,10 @@ runs:
     - name: Validate version format
       run: |
         VERSION=$(node -p "require('./package.json').version")
-        if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-          echo "Version format is invalid. Please follow semver format (x.y.z)"
-          exit 1
+        if git rev-parse "$TAG" >/dev/null 2>&1; then
+          echo "Tag $TAG already exists, skipping tag creation."
+        else
+          git tag -a $TAG -m "Release version $TAG"
         fi
       shell: bash
       
@@ -33,5 +34,6 @@ runs:
       shell: bash
 
     - name: Push tags to GitHub
-      run: git push --tags
+      run: |
+        git push --tags || { echo "Failed to push tags"; exit 1; }
       shell: bash
